# -*- coding: utf-8 -*-
"""LUDay01assign02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qdWlPryFWgkKMGZy3qcuI1Kb17Pt6CFG
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
# %matplotlib inline

days = [1,2,3,4,5,6,7]
sales_1 = [160,150,140,145,175,165,180]
sales_2 = [70,90,160,150,140,145,175]
plt.figure(figsize=(6,5), dpi=100)
plt.plot(days, sales_1)
plt.plot(days, sales_2)
plt.xlabel("Days of the week")
plt.ylabel("Sales")
plt.title("Sales on each day of the week")
plt.show()